version: '3.1'

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: 'chaco'
      MYSQL_PASSWORD: 'chaco'
      MYSQL_DATABASE: 'chaco'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
